### ISSUE TITLE
undefined method order_from_params for #<Administrate::Field::NestedHasMany>

### ISSUE THREAD

**Issue by aksharj** [nickcharlton/administrate-field-nested_has_many#36]
Hi All,

I have two models `DashboardParameterKey` which `has_many` `DashboardParameterValue`. 
I am facing an issue where I am unable to add / edit DashboardParameterKey records and see this exception `undefined method order_from_params for #<Administrate::Field::NestedHasMany:0x00007fb5a080e5f0> excluded from capture: DSN not set`

below is my relevant code

```
class DashboardParameterKey < ApplicationRecord
  has_many :dashboard_parameter_values, dependent: :destroy
  accepts_nested_attributes_for :dashboard_parameter_values, allow_destroy: true, reject_if: :all_blank
end

class DashboardParameterValue < ApplicationRecord
  belongs_to :dashboard_parameter_key
end

require "administrate/base_dashboard"
class DashboardParameterKeyDashboard < Administrate::BaseDashboard 
    ATTRIBUTE_TYPES = {
     dashboard_parameter_values: Field::NestedHasMany,
    }.freeze
end
```

Any help in addressing the issue will be really great, thanks.

**Comment by sedubois** [comment]
The term "DSN" makes me think of the sentry-raven error reporter ([doc](https://github.com/getsentry/raven-ruby#raven-only-runs-when-sentry_dsn-is-set)), I see that Administrate [uses](https://github.com/thoughtbot/administrate/blob/656987b4d993e3e363f129ce72cb0a5a5a5dc806/Gemfile#L12) that gem (I guess for its example app) but I don't know how it could be the cause of what you observe. The exact error message you got seems to be thrown here:
https://github.com/getsentry/raven-ruby/blob/7121d3cf845b1b5769cd4d5f7d7ccf37b38518c6/lib/raven/instance.rb#L107

You may find more information by looking at the stack trace of the error.

**Comment by pablobm** [comment]
I think @sedubois is on to something there. Also @aksharj, would it be possible to paste the whole exception trace? Thank you,

**Comment by aksharj** [comment]
Hi @pablobm @sedubois many thanks for your reply. Here is the full exception trace. Any help in fixing this would be really really great.

```
undefined method `order_from_params' for #<Administrate::Field::NestedHasMany:0x00007fe2c8d6ec70> excluded from capture: DSN not set
  
ActionView::Template::Error (undefined method `order_from_params' for #<Administrate::Field::NestedHasMany:0x00007fe2c8d6ec70>):
    19: %>
    20: 
    21: <% if field.resources.any? %>
    22:   <% order = field.order_from_params(params.fetch(field.name, {})) %>
    23:   <% page_number = params.fetch(field.name, {}).fetch(:page, nil) %>
    24:   <%= render(
    25:     "collection",
  
administrate-field-nested_has_many (1.1.0) app/views/fields/nested_has_many/_show.html.erb:22:in `___sers_imcglobal__rvm_gems_ruby_______gems_administrate_field_nested_has_many_______app_views_fields_nested_has_many__show_html_erb__514099133466338727_70305991622440'
actionview (5.2.3) lib/action_view/template.rb:159:in `block in render'
activesupport (5.2.3) lib/active_support/notifications.rb:170:in `instrument'
actionview (5.2.3) lib/action_view/template.rb:354:in `instrument_render_template'
actionview (5.2.3) lib/action_view/template.rb:157:in `render'
xray-rails (0.3.2) lib/xray/engine.rb:27:in `render_with_xray'
actionview (5.2.3) lib/action_view/renderer/partial_renderer.rb:344:in `block in render_partial'
actionview (5.2.3) lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
activesupport (5.2.3) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.3) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.3) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.2.3) lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
actionview (5.2.3) lib/action_view/renderer/partial_renderer.rb:333:in `render_partial'
actionview (5.2.3) lib/action_view/renderer/partial_renderer.rb:312:in `render'
actionview (5.2.3) lib/action_view/renderer/renderer.rb:49:in `render_partial'
actionview (5.2.3) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.2.3) lib/action_view/helpers/rendering_helper.rb:33:in `render'
/Users/imcglobal/.rvm/gems/ruby-2.5.3/bundler/gems/administrate-710850922a8e/app/helpers/administrate/application_helper.rb:7:in `render_field'
/Users/imcglobal/.rvm/gems/ruby-2.5.3/bundler/gems/administrate-710850922a8e/app/views/administrate/application/show.html.erb:46:in `block in ___sers_imcglobal__rvm_gems_ruby_______bundler_gems_administrate__________a_e_app_views_administrate_application_show_html_erb__2740327399816530191_70306004580360'
/Users/imcglobal/.rvm/gems/ruby-2.5.3/bundler/gems/administrate-710850922a8e/app/views/administrate/application/show.html.erb:37:in `each'
/Users/imcglobal/.rvm/gems/ruby-2.5.3/bundler/gems/administrate-710850922a8e/app/views/administrate/application/show.html.erb:37:in `___sers_imcglobal__rvm_gems_ruby_______bundler_gems_administrate__________a_e_app_views_administrate_application_show_html_erb__2740327399816530191_70306004580360'
actionview (5.2.3) lib/action_view/template.rb:159:in `block in render'
activesupport (5.2.3) lib/active_support/notifications.rb:170:in `instrument'
actionview (5.2.3) lib/action_view/template.rb:354:in `instrument_render_template'
actionview (5.2.3) lib/action_view/template.rb:157:in `render'
xray-rails (0.3.2) lib/xray/engine.rb:27:in `render_with_xray'
actionview (5.2.3) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (5.2.3) lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
activesupport (5.2.3) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.3) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.3) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.2.3) lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
actionview (5.2.3) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (5.2.3) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (5.2.3) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (5.2.3) lib/action_view/renderer/template_renderer.rb:16:in `render'
actionview (5.2.3) lib/action_view/renderer/renderer.rb:44:in `render_template'
actionview (5.2.3) lib/action_view/renderer/renderer.rb:25:in `render'
actionview (5.2.3) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.2.3) lib/action_controller/metal/streaming.rb:219:in `_render_template'
actionview (5.2.3) lib/action_view/rendering.rb:84:in `render_to_body'
actionpack (5.2.3) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.2.3) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (5.2.3) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (5.2.3) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.2.3) lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
activesupport (5.2.3) lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/Users/imcglobal/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
activesupport (5.2.3) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (5.2.3) lib/action_controller/metal/instrumentation.rb:46:in `block in render'
actionpack (5.2.3) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.2.3) lib/active_record/railties/controller_runtime.rb:31:in `cleanup_view_runtime'
actionpack (5.2.3) lib/action_controller/metal/instrumentation.rb:45:in `render'
/Users/imcglobal/.rvm/gems/ruby-2.5.3/bundler/gems/administrate-710850922a8e/app/controllers/administrate/application_controller.rb:24:in `show'
actionpack (5.2.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.3) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.3) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.3) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.3) lib/active_support/callbacks.rb:109:in `block in run_callbacks'
sentry-raven (2.9.0) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
activesupport (5.2.3) lib/active_support/callbacks.rb:118:in `instance_exec'
activesupport (5.2.3) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
ahoy_matey (3.0.0) lib/ahoy/controller.rb:45:in `set_ahoy_request_store'
activesupport (5.2.3) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
activesupport (5.2.3) lib/active_support/callbacks.rb:136:in `run_callbacks'
actionpack (5.2.3) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.3) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.3) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.3) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.3) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.3) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.3) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.3) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.3) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.3) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.3) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.3) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.3) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.3) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.3) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.3) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.3) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.3) lib/action_dispatch/routing/route_set.rb:840:in `call'
apipie-rails (0.5.15) lib/apipie/static_dispatcher.rb:66:in `call'
xray-rails (0.3.2) lib/xray/middleware.rb:38:in `call'
apipie-rails (0.5.15) lib/apipie/extractor/recorder.rb:137:in `call'
rack-attack (5.4.2) lib/rack/attack.rb:182:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.0.7) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
actionpack (5.2.3) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.3) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.3) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
ahoy_matey (3.0.0) lib/ahoy/engine.rb:22:in `call_with_quiet_ahoy'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
sentry-raven (2.9.0) lib/raven/integrations/rack.rb:51:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'

```

**Comment by sedubois** [comment]
@aksharj your Administrate gem seems to be pinned to revision `710850922a8e` which I was unable to locate (latest is 0.13.0), and your `administrate-field-nested_has_many` is version 1.1.0 (latest is 1.2.0). You could give a try again after updating both gems to the latest released versions?

**Comment by aksharj** [comment]
hi @sedubois, thats awesome, many thanks for your reply. that fixed it.
