### ISSUE TITLE
Polymorphic relationships on children aren't handled well

### ISSUE THREAD

**Issue by efatsi** [nickcharlton/administrate-field-nested_has_many#38]
Not sure if this issue should live here or on the main administrate repo, but I ran into an edge case with this gem and a nested polymorphic relationship, and came up with a workaround that I thought would benefit the community by being discoverable. This was my setup:

### Model Definitions
```rb
class School < ApplicationRecord
  has_many :students
  accepts_nested_attributes_for :students
end

class Student < ApplicationRecord
  belongs_to :school

  # Students can be obsessed with a school, or another student
  belongs_to :obsession, polymorphic: true, optional: true
end
```

### Dashboard definitions
```rb
class SchoolDashboard < Administrate::BaseDashboard
  ATTRIBUTE_TYPES = {
    name: Field::String,
    students: Field::NestedHasMany
  }

  FORM_ATTRIBUTES = [
    :name,
    :students,
  ]
end

class StudentDashboard < Administrate::BaseDashboard
  ATTRIBUTE_TYPES = {
    school: Field::BelongsTo,
    name: Field::String,
    obsession: Field::Polymorphic.with_options(
      classes: [School, Student]
    )
  }

  FORM_ATTRIBUTES = [
    :school,
    :name,
    :obsession,
  ]
end
```

## The error:

The form would load as you would expect, but on form submission, an error within ActiveRecord was thrown:

```
NoMethodError (undefined method `primary_key' for ActiveSupport::HashWithIndifferentAccess:Class):

activerecord (6.0.3) lib/active_record/reflection.rb:322:in `primary_key'
activerecord (6.0.3) lib/active_record/reflection.rb:468:in `association_primary_key'
activerecord (6.0.3) lib/active_record/associations/belongs_to_association.rb:104:in `primary_key'
activerecord (6.0.3) lib/active_record/associations/belongs_to_association.rb:100:in `replace_keys'
activerecord (6.0.3) lib/active_record/associations/belongs_to_polymorphic_association.rb:18:in `replace_keys'
activerecord (6.0.3) lib/active_record/associations/belongs_to_association.rb:71:in `replace'
activerecord (6.0.3) lib/active_record/associations/singular_association.rb:17:in `writer'
activerecord (6.0.3) lib/active_record/associations/builder/association.rb:108:in `obsession='
activemodel (6.0.3) lib/active_model/attribute_assignment.rb:50:in `public_send'
activemodel (6.0.3) lib/active_model/attribute_assignment.rb:50:in `_assign_attribute'
activerecord (6.0.3) lib/active_record/attribute_assignment.rb:29:in `block in assign_nested_parameter_attributes'
activerecord (6.0.3) lib/active_record/attribute_assignment.rb:29:in `each'
activerecord (6.0.3) lib/active_record/attribute_assignment.rb:29:in `assign_nested_parameter_attributes'
activerecord (6.0.3) lib/active_record/attribute_assignment.rb:23:in `_assign_attributes'
activemodel (6.0.3) lib/active_model/attribute_assignment.rb:35:in `assign_attributes'
activerecord (6.0.3) lib/active_record/nested_attributes.rb:551:in `assign_to_or_mark_for_destruction'
activerecord (6.0.3) lib/active_record/nested_attributes.rb:516:in `block in assign_nested_attributes_for_collection_association'
activerecord (6.0.3) lib/active_record/nested_attributes.rb:494:in `each'
activerecord (6.0.3) lib/active_record/nested_attributes.rb:494:in `assign_nested_attributes_for_collection_association'
activerecord (6.0.3) lib/active_record/nested_attributes.rb:372:in `students_attributes='
activemodel (6.0.3) lib/active_model/attribute_assignment.rb:50:in `public_send'
activemodel (6.0.3) lib/active_model/attribute_assignment.rb:50:in `_assign_attribute'
activerecord (6.0.3) lib/active_record/attribute_assignment.rb:29:in `block in assign_nested_parameter_attributes'
activerecord (6.0.3) lib/active_record/attribute_assignment.rb:29:in `each'
activerecord (6.0.3) lib/active_record/attribute_assignment.rb:29:in `assign_nested_parameter_attributes'
activerecord (6.0.3) lib/active_record/attribute_assignment.rb:23:in `_assign_attributes'
activemodel (6.0.3) lib/active_model/attribute_assignment.rb:35:in `assign_attributes'
activerecord (6.0.3) lib/active_record/persistence.rb:620:in `block in update'
activerecord (6.0.3) lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
activerecord (6.0.3) lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
activerecord (6.0.3) lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
activesupport (6.0.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
activesupport (6.0.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
activesupport (6.0.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
activesupport (6.0.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
activesupport (6.0.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
activerecord (6.0.3) lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
activerecord (6.0.3) lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
activerecord (6.0.3) lib/active_record/transactions.rb:212:in `transaction'
activerecord (6.0.3) lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
activerecord (6.0.3) lib/active_record/persistence.rb:619:in `update'
administrate (0.13.0) app/controllers/administrate/application_controller.rb:60:in `update'
```

## Why the error is thrown

I traced the root of this to the fact that the `resource_params` that were ultimately passed to the model instance didn't properly convert the polymorphic params nested within the has_many params.

Params were:
```
{"school" => {
  "name" => "Other",
  "students_attributes" => {
    "0" => {
      "school_id" => "2",
      "name" => "Le Traitor",
      "obsession" => { "type" => "Administrate::Field::Polymorphic", "value" => "gid://dummy/School/1" }
    }
  }
}
```

Params should have been:
```
{"school" => {
  "name" => "Other",
  "students_attributes" => {
    "0" => {
      "school_id" => "2",
      "name" => "Le Traitor",
      "obsession" => #<School:0x00007fcbcde14358 id: 1, name: "La Ferme du Bec Hellouin" ...>
    }
  }
}
```

In the `Admin::ApplicationController` within administrate core, there's the [`read_param_value(data)`](https://github.com/thoughtbot/administrate/blob/master/app/controllers/administrate/application_controller.rb#L140-L150) method which is supposed to recognize polymorphic parameters (by checking for the `type` key) and replace the hash with an actual resource. The default implementation only does so at the top level however, and that logic is not applied to nested parameters.

## My hacky fix:

In my application, I wrote an override for the `read_param_value` method which recursively calls itself if it sees a set of params that does not have a `type` attribute:

```rb
def read_param_value(data)
  if data.is_a?(ActionController::Parameters) && !data[:type]
    data.transform_values { |v| read_param_value(v) }
  else
    super
  end
end
```

## What a permanent fix would look like:

I imagine a PR to the main administrate repo to make the `read_param_value` method recursive is the "proper" fix. Although I don't know what the protocol is for making updates to the base repo specifically for the case that a separate library is used. If the base library is meant for the base use case, and this doesn't qualify, then perhaps some code in this library that overrides that default method (this approach seems like too much indirection to me personally).

I've demonstrated the bug / hack fix with some commits on this repo. You can see the comparisons / commit history here: https://github.com/nickcharlton/administrate-field-nested_has_many/compare/master...efatsi:master. And the transition from a [failing spec](https://app.circleci.com/pipelines/github/efatsi/administrate-field-nested_has_many/7/workflows/16226925-1126-436a-8586-197641cc4f77/jobs/7) to a [passing spec](https://app.circleci.com/pipelines/github/efatsi/administrate-field-nested_has_many/8/workflows/2caf94d8-a805-4e55-a926-94db6da8eb08/jobs/8) thanks to the override.

**Comment by nickcharlton** [comment]
Huh, interesting! Thanks for what you’ve done here, it’s very clear to understand what’s going on.

I think you’re right in that we should look at fixing this on Administrate itself, even if it feels weird to fix it for a custom field. Would you be able to open a PR over there for this?
